export type User = {
    id: string,
    username: string,
    email: string,
    password: string,
    profilePicture: string,
    notificationSound: string,
    dogName: string,
    location: string,
    friendsArray: string[],
    friendRequestsArray: string[],
    pendingFriendRequestsArray: string[],
    pendingFriendRequestsSentArray: string[],
    blockedUsersArray: string[],
    groupsArray: string[],
    groupInvitesArray: string[],
    pendingGroupInvitesArray: string[],
    pendingGroupInvitesSentArray: string[],
    blockedGroupsArray: string[],
    postsArray: string[],
};
